version: '3'
services:
  dash_postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: service_account
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: vuln_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data


  trivy:
    image: aquasec/trivy:latest
    environment:
      - TRIVY_NEW_JSON=true
    volumes:
      - ./results:/results  # Maps a local folder to store results
      - ./cloned_repos:/cloned_repos  # Directory to store cloned repositories
    entrypoint: >
      sh -c "
        [ ! -d /cloned_repos/django.nV ] && git clone https://github.com/vulnerable-apps/django.nV.git /cloned_repos/django.nV;
        [ ! -d /cloned_repos/dvpwa ] && git clone https://github.com/anxolerd/dvpwa.git /cloned_repos/dvpwa;
        [ ! -d /cloned_repos/vulnerable-spring-boot-application ] && git clone https://github.com/Contrast-Security-OSS/vulnerable-spring-boot-application.git /cloned_repos/vulnerable-spring-boot-application;

        trivy fs --format json --output /results/djangonV_results.json /cloned_repos/django.nV;
        trivy fs --format json --output /results/dvpwa_results.json /cloned_repos/dvpwa;
        trivy fs --format json --output /results/vulnerable-spring-boot-application_results.json /cloned_repos/vulnerable-spring-boot-application
      "
volumes:
  postgres_data:

